trigger:  
  branches:
    include:
      - main 
      - dev

stages: 

- stage: Build
  jobs:
   - job: Build
     displayName: 'Build job'
     pool:
      vmImage:  'windows-latest'

# Build Stage
     steps:
        - task: UseDotNet@2
          inputs:
            packageType: 'sdk'
            version: '10.x'
            installationPath: $(Agent.ToolsDirectory)/dotnet

        - script: |
              dotnet build --configuration Release
          displayName: "Build Solution"

        - script: | 
            dotnet publish -c Release -o $(Build.ArtifactStagingDirectory)
          displayName: 'Publish Artifacts'

        - task: PublishBuildArtifacts@1
          inputs:
            PathtoPublish: $(Build.ArtifactStagingDirectory)
            ArtifactName: drop
            publishLocation: 'Container'
          


- stage: Deploy 
  jobs:
    - deployment: DeployWebApp
      displayName: "Deploy to Azure app service"
      environment: 'production'
      strategy:
        runOnce:         
          deploy:
            steps:
            - download: current
              artifact: drop

            - task: AzureWebApp@1
              inputs:
                azureSubscription: 'sportsonAPI'
                appType: 'webApp'
                appName: 'sportsonAPI'
                package: $(Pipeline.Workspace)/drop
