# Vilken branch som triggar pipelinen eller none= manuell start
trigger:
- dev

# Skapar en virtuell maskin med en windows image
# För self-hosted byt ut wmImage mot name: 'Namnet_DinAgentPool' 
pool:
  name: Default

# En variabel med värde som kan användas flera gånger
variables:
  buildConfiguration: 'Release'

# De olika stegen (steps och tasks) i skriptet (hämta kod-förbered-bygg-deploya)
steps:

# Hämta koden från samma repo(self) som YAML filen ligger i. För self-hosted lägg
# även till clean: true . Ny rad efter checkout. Det rensar tidigare körning
- checkout: self
  clean: true
# Installera .NET SDK och välj .NET 10 (x=alla versioner av den)
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '10.x'

# Restore av dependencies
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'
    projects: '**/*.csproj'

# Gör build av projekt
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '**/*.csproj'
    arguments: '--configuration $(buildConfiguration)'

