// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsonView.API.Data;

#nullable disable

namespace SportsonView.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260414203517_SeedImportantDates")]
    partial class SeedImportantDates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SportsonView.API.Data.Entities.ImportantDate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsReminderActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TimeLabel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ImportantDates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsReminderActive = true,
                            StartDate = new DateTime(2026, 5, 4, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeLabel = "08.00 - 09.00",
                            Title = "Frukostmöte: Nytt förmånspaket"
                        },
                        new
                        {
                            Id = 2,
                            IsReminderActive = false,
                            StartDate = new DateTime(2026, 5, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeLabel = "Hela dagen",
                            Title = "Kampanjstart: Sommarcyklar 2026"
                        },
                        new
                        {
                            Id = 3,
                            IsReminderActive = true,
                            StartDate = new DateTime(2026, 5, 15, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeLabel = "13.00 - 15.00",
                            Title = "Personalmöte - Volvo tjänstebilar"
                        },
                        new
                        {
                            Id = 4,
                            EndDate = new DateTime(2026, 5, 29, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            IsReminderActive = true,
                            StartDate = new DateTime(2026, 5, 26, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeLabel = "09.00 - 17.00",
                            Title = "Utbildning: Service av elmotorer"
                        },
                        new
                        {
                            Id = 5,
                            IsReminderActive = true,
                            StartDate = new DateTime(2026, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeLabel = "Senast kl 16.00",
                            Title = "Deadline: Beställning Volvo-kläder"
                        },
                        new
                        {
                            Id = 6,
                            IsReminderActive = false,
                            StartDate = new DateTime(2026, 6, 19, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeLabel = "17.00 - Sent",
                            Title = "Sommarfest med teamet"
                        },
                        new
                        {
                            Id = 7,
                            IsReminderActive = true,
                            StartDate = new DateTime(2026, 6, 25, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TimeLabel = "07.00 - 12.00",
                            Title = "Inventering av butikslager"
                        });
                });

            modelBuilder.Entity("SportsonView.API.Data.Entities.NewsArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly>("PublishedDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("NewsArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Daniel Andersson",
                            Body = "Som en del i vårt kontinuerliga arbete med att stärka säkerheten kring företagets digitala tillgångar, kommer vi att genomföra en stor uppgradering av inloggningssystemet. \nFrån och med måndag nästa vecka krävs tvåfaktorsautentisering (2FA) för samtliga anställda som arbetar på huvudkontoret och i våra butiker. \nDetta innebär att du utöver ditt vanliga lösenord även behöver bekräfta din identitet via Microsoft Authenticator-appen på din arbetstelefon. \nVi har sett en ökad mängd nätfiskeförsök mot liknande företag i branschen och väljer därför att ligga steget före för att skydda vår data. \nVi rekommenderar alla att ladda ner appen redan idag och följa den steg-för-steg-guide som finns publicerad på startsidan under IT-support. \nOm du saknar en arbetstelefon eller har problem med att installera applikationen, vänligen kontakta helpdesk senast fredag kl 15:00. \nDet nya systemet kommer även att göra det enklare att nå våra interna system hemifrån på ett säkert sätt utan att använda krångliga VPN-lösningar. \nVid första inloggningen på måndag kommer du att mötas av en installationsguide som tar ungefär två minuter att genomföra helt på egen hand. \nVi tackar för ert tålamod och samarbete i detta viktiga steg för att göra Sportson till en tryggare arbetsplats för oss alla digitalt sett. \nTillsammans säkerställer vi att vår kunddata och interna information förblir skyddad mot obehöriga intrång och framtida säkerhetshot.",
                            Category = "IT",
                            ImageUrl = "https://sportsonsbilder.blob.core.windows.net/news-images/IT.png",
                            PublishedDate = new DateOnly(2026, 4, 1),
                            Title = "Uppdatering av intranätet och IT-säkerhet"
                        },
                        new
                        {
                            Id = 2,
                            Author = "Sara Lindberg",
                            Body = "Vi har tyvärr mottagit tråkiga besked från våra logistikpartners gällande de kommande leveranserna av elcyklar från Crescent och Monark. \nPå grund av oväntade störningar i den globala fraktkedjan och tillfällig brist på specifika växelkomponenter från Shimano, dröjer leveransen. \nFörseningen beräknas just nu vara cirka två till tre veckor från det ursprungliga datumet som kommunicerades ut till butikerna i mars. \nDetta påverkar främst våra mest populära pendlarmodeller, vilket är beklagligt då vi vet att många kunder väntar ivrigt på sina cyklar. \nInköpsavdelningen arbetar dygnet runt med att hitta alternativa fraktvägar för att försöka korta ner väntetiden så mycket som det går. \nVi ber alla butikssäljare att vara proaktiva och ringa upp de kunder som har lagt handpenning för att informera om det aktuella läget. \nFör att kompensera de väntande kunderna har ledningen beslutat att vi erbjuder en gratis förstaårsservice till alla som drabbas av förseningen. \nVi skickar ut ett färdigt manus för hur detta ska kommuniceras till kunderna via e-post under eftermiddagen så att budskapet blir enhetligt. \nHåll ett öga på lagersystemet där vi kommer att uppdatera förväntade ankomstdatum så fort vi får nya bekräftelser från våra leverantörer i Asien. \nVi tackar för er förståelse och för ert hårda arbete med att hålla kundrelationerna goda trots dessa utmaningar utanför vår kontroll.",
                            Category = "Inköp",
                            ImageUrl = "https://sportsonsbilder.blob.core.windows.net/news-images/Inköp.png",
                            PublishedDate = new DateOnly(2026, 4, 2),
                            Title = "Leveransförseningar av årets elcyklar"
                        },
                        new
                        {
                            Id = 3,
                            Author = "Erik Markström",
                            Body = "Nu är det äntligen dags att rulla ut årets absolut största och viktigaste kampanj, vår stora vårstart som kickar igång cykelsäsongen på allvar. \nMarknadsavdelningen har under flera månader arbetat med att ta fram ett koncept som verkligen sticker ut i bruset och lockar folk till butik. \nKampanjen startar officiellt den 15 april och kommer att synas stort i både TV, radio och i alla våra sociala mediekanaler under sex veckor. \nVi har tagit fram helt nytt butiksmaterial i form av vepor, gatupratare och digitala banners som börjar levereras till er under veckan. \nMålet med årets kampanj är att visa på friheten med att cykla och hur enkelt det är att byta ut bilen mot en modern elcykel i vardagen. \nVi vill uppmuntra alla butiker att planera in lokala 'provkörningsdagar' under helgerna för att låta så många som möjligt testa våra nyheter. \nGlöm inte att dokumentera era lokala event och skicka bilder till marknadsteamet, vi vill gärna visa upp det fantastiska jobbet ni gör ute i landet. \nAllt kampanjmaterial finns även tillgängligt för nedladdning i den gemensamma bildbanken om ni vill göra egna lokala annonser i tidningen. \nSäkerställ att butiksutställningen är toppad och att alla kampanjcyklar är monterade och redo för omedelbar provkörning av våra kunder. \nNu kör vi så det ryker och ser till att våren 2026 blir den mest framgångsrika perioden i Sportsons historia hittills!",
                            Category = "Marknad",
                            ImageUrl = "https://sportsonsbilder.blob.core.windows.net/news-images/Marknad.png",
                            PublishedDate = new DateOnly(2026, 4, 3),
                            Title = "Vårkampanjen 2026 drar äntligen igång!"
                        },
                        new
                        {
                            Id = 4,
                            Author = "Mikael Verkstadsson",
                            Body = "För att bibehålla vår status som auktoriserad servicepartner för Shimano, inför vi nu skärpta krav på certifiering för all verkstadspersonal. \nDen tekniska utvecklingen går snabbt, särskilt inom elsystem och digital diagnostik, vilket kräver att vi ständigt uppdaterar vår kunskap. \nFrån och med den 1 maj kommer endast certifierade mekaniker att få utföra garantiarbeten på de nya EP8- och STEPS-systemen i våra verkstäder. \nVi har därför bokat in en serie obligatoriska utbildningsdagar som kommer att hållas digitalt samt fysiskt på tre olika platser i Sverige. \nAnmälan görs via länken i personalportalen och vi ser gärna att minst två mekaniker från varje butik deltar i de första omgångarna i vår. \nUtbildningen täcker allt från avancerad felsökning till korrekt hantering av batterier och mjukvaruuppdateringar för framtidens elcyklar. \nEfter avslutad och godkänd kurs får varje deltagare ett personligt certifikat och butiken får en dekal att sätta upp som visar vår expertis. \nVi investerar i denna utbildning för att vi vet att vår kunskap är det som gör att kunderna känner sig trygga med att lämna in sin cykel hos oss. \nVarje utbildningstillfälle tar en hel dag och vi ersätter butikerna för den tid som personalen är borta från den ordinarie produktionen. \nSe till att boka in era platser redan idag då antalet fysiska platser är begränsade för att säkerställa högsta kvalitet på undervisningen.",
                            Category = "Verkstad",
                            ImageUrl = "https://sportsonsbilder.blob.core.windows.net/news-images/Verkstad.png",
                            PublishedDate = new DateOnly(2026, 4, 4),
                            Title = "Nya strikta krav på Shimano-certifiering"
                        },
                        new
                        {
                            Id = 5,
                            Author = "Marknadsteamet",
                            Body = "Gör dig redo för den ultimata cykelsäsongen med vårt största erbjudande någonsin på marknadens absolut bästa och mest moderna elcyklar. \nJust nu firar vi vårens ankomst med en fantastisk kampanj där vi erbjuder hela 20% rabatt på samtliga elcyklar som vi har i butikslagret. \nOavsett om du letar efter en snabb pendlarcykel för jobbet, en robust lådcykel för familjen eller en kraftfull MTB, så har vi modellen. \nDetta är ett unikt tillfälle att uppgradera ditt sätt att resa och samtidigt göra en bra affär inför de soliga dagarna som ligger framför oss. \nErbjudandet gäller alla märken såsom Scott, Specialized, Trek och Crescent, men bara så långt lagret räcker i din lokala Sportson-butik. \nKom in och prata med våra experter som hjälper dig att hitta rätt storlek och motoralternativ som passar just dina specifika behov. \nVid köp av en ny elcykel ingår som alltid vår trygga livstidsgaranti på ramen och en kostnadsfri första säkerhetskontroll efter tre månader. \nVi erbjuder även förmånlig finansiering och räntefri delbetalning för att göra det så enkelt som möjligt för dig att börja cykla direkt. \nVälkommen in till oss för en provtur som kommer att förändra din syn på vardagsmotion och pendling – känn vinden i håret utan ansträngning. \nKampanjen pågår under en begränsad tid, så vänta inte för länge med att besöka oss och säkra din favoritmodell innan den tar slut i lager!",
                            Category = "Campaign",
                            ImageUrl = "https://sportsonsbilder.blob.core.windows.net/news-images/Campaign.png",
                            PublishedDate = new DateOnly(2026, 4, 12),
                            Title = "Vårkampanj: 20% rabatt på alla Elcyklar i lager!"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
